name: .NET Core Master
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: [self-hosted, windows]
    steps:
    - uses: actions/checkout@v2
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 6
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Setup Nuget
      uses: nuget/setup-nuget@v1
      
    - name: Download References
      run: wget "https://cdn.cedmod.nl/files/References.zip" -outfile "References.zip"
      
    - name: Unzip References Zip
      run: Expand-Archive References.zip -DestinationPath ./
      
    - name: Restore Packages
      run: nuget restore CedMod.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore CedMod.sln
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
       name: CedMod Build Results
       path: ${{ github.workspace }}/bin/Release/CedMod*.dll
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: CHANGELOG.md
        tag_name: ${{ steps.short-sha.outputs.sha }}
        files: |
          ${{ github.workspace }}/bin/Release/CedModV3.dll
          ${{ github.workspace }}/bin/Release/CedMod-QuerySystem.dll
          ${{ github.workspace }}/bin/Release/CedMod-EventManager.dll
